import Extract

extract = Extract.Extract()



print(extract.main('幫我打給小絨'))
print(' ')
print(extract.main('打給0800000123'))
print(' ')
print(extract.main('幫我打給'))
print(' ')
print(extract.main('查看下一個行程'))
print(' ')
print(extract.main('查看行事曆十二月三日'))
print(' ')
print(extract.main('新增行事曆12月3號12點到13點家庭聚餐'))
print(' ')
print(extract.main('新增行事曆每週二兩點兩分家庭聚餐'))
print(' ')
print(extract.main('新增行事曆每天18點健身'))
print(' ')
# print(extract.main('新增提醒 12月3號 12點 家庭聚餐'))
# print(' ')
print(extract.main('查看下一個行程'))
print(' ')
print(extract.main('天氣查詢'))
print(' ')
print(extract.main('天氣查詢12月3日'))
print(' ')
print(extract.main('天氣查詢台北'))
print(' ')
print(extract.main('天氣查詢12月五日八點十三的台北'))
print(' ')
print(extract.main('開啟藍芽'))
print(' ')
print(extract.main('關閉藍芽'))
print(' ')
print(extract.main('播放鄧紫棋的光年之外'))
print(' ')
print(extract.main('暫停播放'))
print(' ')
print(extract.main('停止音樂'))
print(' ')
print(extract.main('現在在播的是什麼'))
print(' ')
print(extract.main('幫我一直播放'))
print(' ')
print(extract.main('系統音量調大聲'))
print(' ')
print(extract.main('系統音量調小聲10趴'))
print(' ')
print(extract.main('系統音量調成兩百'))
print(' ')
print(extract.main('音樂音量調大聲負10'))
print(' ')
print(extract.main('音樂音量調小聲18'))
print(' ')
print(extract.main('音樂音量調成500'))
print(' ')
print(extract.main('音量調大聲-18'))
print(' ')
print(extract.main('音量調小聲0'))
print(' ')
print(extract.main('音量調成'))
print(' ')
print(extract.main('啟動即時翻譯'))
print(' ')
print(extract.main('啟動即時翻譯中文翻法文'))
print(' ')
